<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>8bcbf89d-e778-4eef-a7ee-5aaf7c8bb6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.closeModal > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ZipCodeDisclaimer']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZipCodeDisclaimer&quot;)/a[@class=&quot;closeModal&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ZipCodeDisclaimer']/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
